# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x08services\"3\n\x08GetBlock\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\r\n\x05\x62lock\x18\x03 \x01(\x05\"\x12\n\x10GetBlockResponse2I\n\x08Services\x12=\n\tSendBlock\x12\x12.services.GetBlock\x1a\x1a.services.GetBlockResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBLOCK']._serialized_start=28
  _globals['_GETBLOCK']._serialized_end=79
  _globals['_GETBLOCKRESPONSE']._serialized_start=81
  _globals['_GETBLOCKRESPONSE']._serialized_end=99
  _globals['_SERVICES']._serialized_start=101
  _globals['_SERVICES']._serialized_end=174
# @@protoc_insertion_point(module_scope)
